apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloth-app
  labels:
    app: cloth-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cloth-app
  template:
    metadata:
      labels:
        app: cloth-app
    spec:
      containers:
        - name: cloth-app
          image: shubhamkalsait1/cloth-app:latest
          ports:
            - containerPort: 80   
  strategy:
    type: RollingUpdate
